# Generated by Django 5.2.9 on 2025-12-03 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='vehicle_type',
            field=models.CharField(choices=[('TWO', 'Two Wheeler'), ('THREE', 'Three Wheeler'), ('FOUR', 'Four Wheeler')], max_length=6),
        ),
    ]
