# Generated by Django 5.2.9 on 2025-12-03 14:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0002_auto_populate_vehicletypes'),
        ('vehicles', '0003_vehicletype_remove_vehicle_vehicle_type_and_more'),
    ]

    operations = [
    ]
