# Generated by Django 5.2.9 on 2025-12-03 14:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0004_merge_20251203_2025'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vehicle',
            old_name='vehicle_type_id',
            new_name='vehicle_type',
        ),
    ]
