# Generated by Django 5.2.9 on 2025-12-04 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0006_authtoken'),
    ]

    operations = [
        migrations.AlterField(
            model_name='authtoken',
            name='key',
            field=models.CharField(db_index=True, max_length=128, unique=True),
        ),
    ]
