# Generated by Django 5.2.9 on 2026-01-16 16:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('garages', '0004_customer_whatsapp_number'),
        ('services', '0001_initial'),
        ('vehicles', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceReminder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reminder_day', models.PositiveSmallIntegerField(choices=[(7, '7 Days Before'), (3, '3 Days Before'), (1, '1 Day Before')], help_text='How many days before next service date')),
                ('scheduled_for', models.DateField(help_text='Date on which reminder should be sent (checked at 9 AM)')),
                ('channel', models.CharField(choices=[('WHATSAPP', 'WhatsApp'), ('EMAIL', 'Email'), ('BOTH', 'WhatsApp + Email')], default='BOTH', max_length=20)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('PROCESSING', 'Processing'), ('SENT', 'Sent'), ('FAILED', 'Failed')], default='PENDING', max_length=15)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('failure_reason', models.TextField(blank=True, null=True)),
                ('provider_message_id', models.CharField(blank=True, help_text='WhatsApp / Email provider reference ID', max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_reminders', to='garages.customer')),
                ('service_record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reminders', to='services.servicerecord')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_reminders', to='vehicles.vehicle')),
            ],
            options={
                'db_table': 'service_reminders',
                'indexes': [models.Index(fields=['scheduled_for', 'status'], name='service_rem_schedul_b7177d_idx')],
                'unique_together': {('service_record', 'reminder_day')},
            },
        ),
    ]
