# Generated by Django 5.2.9 on 2026-01-18 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_servicereminder'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicereminder',
            name='sent_via',
            field=models.CharField(blank=True, help_text="Channels that actually succeeded (e.g., 'WHATSAPP', 'EMAIL', 'WHATSAPP,EMAIL')", max_length=30, null=True),
        ),
    ]
