# Generated by Django 5.2.9 on 2026-01-06 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('garages', '0002_rename_name_garage_garage_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='garage',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
